### ISSUE TITLE
make available on Bower

### ISSUE THREAD

**Issue by graingert** [JoelSutherland/LESS-Prefixer#15]
These days everyone's doing it.

Also add semver tags to the repo, please

**Comment by graingert** [comment]
yeah, bower's dead now.

**Comment by JoelSutherland** [comment]
Oh -- I closed as this has been added by a contributor.

**Comment by graingert** [comment]
oh well there's no harm if it's not difficult to maintain. It's just something I wouldn't bother adding to projects now that lodash and Angular have abandoned the platform.
