### ISSUE TITLE
CSS filters

### ISSUE THREAD

**Issue by rayshan** [JoelSutherland/LESS-Prefixer#18]
Hi, can we please add prefixes for CSS filters? Currently only `-webkit-` is available for Chrome / Safari / Opera. Firefox implementation is coming:
https://bugzilla.mozilla.org/show_bug.cgi?id=869828

Reference:
https://developer.mozilla.org/en-US/docs/Web/CSS/filter

Not sure if can be combined with https://github.com/JoelSutherland/LESS-Prefixer/issues/5.

**Comment by JoelSutherland** [comment]
It looks like there is decent browser support for this now, so I'll investigate.

**Comment by JoelSutherland** [comment]
Added!

**Comment by rayshan** [comment]
🎉
