### ISSUE TITLE
Please add support for 2 parameters in box-shadow(@arg1,@arg2)

### ISSUE THREAD

**Issue by Andey-d** [JoelSutherland/LESS-Prefixer#47]
Please add support for 2 parameters in box-shadow(@arg1,@arg2)
-------------------

RuntimeError: No matching definition was found for `.box-shadow(6px 6px 8px -2px #d4d4d4, -6px 6px 8px -2px #d4d4d4)` in \Styles\index.less	web	Styles\index.less	24

// sourse code 
 .box-shadow( 6px 6px 8px -2px #d4d4d4, -6px 6px 8px -2px #d4d4d4);

**Comment by JoelSutherland** [comment]
This is handled by LESS itself with a semicolon:

`.box-shadow(0 0 30px rgba(255,0,0,.5), 0 0 20px 20px fadeout(@blue,90%););`
